worspace: ~/dev

remotes:
  - name: github
    user:
      name: <your-user-name>
      email: <your-email>
    clone:
      domain: github.com
    api:
      provider: github
      token: ${GITHUB_TOKEN}

  - name: rust-play
    on_create: |
      cargo init

  - name: go-play
    on_create: |
      go mod init ${NAME}
      echo "package main" > main.go
