workspace: ~/dev

tag_rule:
  patch: v{0}.{1}.{2+}
  minor: v{0}.{1+}.0
  major: v{0+}.0.0
  date: '{%Y}-{%m}-{%d}'

remotes:
  - name: github
    user:
      name: <your-user-name>
      email: <your-email>
    clone:
      domain: github.com
    api:
      provider: github
      token: ${GITHUB_TOKEN}

  - name: rust-play
    on_create:
      - name: Init cargo
        run: cargo init

  - name: go-play
    on_create:
      - name: Init gomod
        run: go mod init ${REPO_NAME}
      - name: main.go
        file: |
          package main

          import "fmt"

          func main() {
          \tfmt.Println("hello world!")
          }
