name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        uses: SebRollen/toml-action@2bd04b06a3ebc3e6a3eb6060de115710cad16cd6 # v1.0.2
        with:
          file: Cargo.toml
          field: package.version

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ steps.get_version.outputs.value }}
